run:
    skip-dirs:
        - oauth2/internal

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/go-withings

linters:
    presets:
        - bugs
        - unused
        - format
        - import
    disable:
        - noctx

